server:
  port: 6002

spring:
  application:
    name: STUDENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    password: Aa@611252
    url: jdbc:mysql://localhost:3306/springdatajpa
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sql:
    init:
      mode: always